[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
community_pot = "BsJDnhJGVdLQ3mxBJ7YCMkkBitKP2RT49zFqR9XsGri1"
lock_vault = "41TexnrHDMV4ASJmqNNFcgQ7RBk6N193yvukfiCzKQmD"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"
