[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
locked_in = "68im45BCfv8sL6WnVVV9JF4edLkB11udeU9EAApNaEx3"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"
