-- 0051: strip deleted Fuel/Ichor mechanics from live course 1 & 2 content.
-- Text-level replace on the stored jsonb (no id/structure changes → safe for enrollments/progress).

do $mig$
begin
  update lesson.lesson_blocks set payload = replace(payload::text, $f0$earning Fuel — is a transaction$f0$, $r0$claiming your yield — is a transaction$r0$)::jsonb where position($f0$earning Fuel — is a transaction$f0$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f0$earning Fuel — is a transaction$f0$, $r0$claiming your yield — is a transaction$r0$)::jsonb where position($f0$earning Fuel — is a transaction$f0$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f1$earning Fuel — is recorded$f1$, $r1$claiming your yield — is recorded$r1$)::jsonb where position($f1$earning Fuel — is recorded$f1$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f1$earning Fuel — is recorded$f1$, $r1$claiming your yield — is recorded$r1$)::jsonb where position($f1$earning Fuel — is recorded$f1$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f2$'value', 'Network Fuel'$f2$, $r2$'value', 'Gas Token'$r2$)::jsonb where position($f2$'value', 'Network Fuel'$f2$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f2$'value', 'Network Fuel'$f2$, $r2$'value', 'Gas Token'$r2$)::jsonb where position($f2$'value', 'Network Fuel'$f2$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f3$Locked USDC. Earned some Fuel.$f3$, $r3$Locked USDC. Kept your flame lit. Earned some yield.$r3$)::jsonb where position($f3$Locked USDC. Earned some Fuel.$f3$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f3$Locked USDC. Earned some Fuel.$f3$, $r3$Locked USDC. Kept your flame lit. Earned some yield.$r3$)::jsonb where position($f3$Locked USDC. Earned some Fuel.$f3$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f4$your USDC, SOL, Fuel records$f4$, $r4$your USDC, SOL, lock and streak records$r4$)::jsonb where position($f4$your USDC, SOL, Fuel records$f4$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f4$your USDC, SOL, Fuel records$f4$, $r4$your USDC, SOL, lock and streak records$r4$)::jsonb where position($f4$your USDC, SOL, Fuel records$f4$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f5$'headers', jsonb_build_array('', 'Fuel', 'Ichor')$f5$, $r5$'headers', jsonb_build_array('', 'Principal', 'Yield')$r5$)::jsonb where position($f5$'headers', jsonb_build_array('', 'Fuel', 'Ichor')$f5$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f5$'headers', jsonb_build_array('', 'Fuel', 'Ichor')$f5$, $r5$'headers', jsonb_build_array('', 'Principal', 'Yield')$r5$)::jsonb where position($f5$'headers', jsonb_build_array('', 'Fuel', 'Ichor')$f5$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f6$jsonb_build_array('What is it?', 'Activity counter', 'Reward counter')$f6$, $r6$jsonb_build_array('What is it?', 'The USDC you locked', 'Interest it earns via Kamino')$r6$)::jsonb where position($f6$jsonb_build_array('What is it?', 'Activity counter', 'Reward counter')$f6$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f6$jsonb_build_array('What is it?', 'Activity counter', 'Reward counter')$f6$, $r6$jsonb_build_array('What is it?', 'The USDC you locked', 'Interest it earns via Kamino')$r6$)::jsonb where position($f6$jsonb_build_array('What is it?', 'Activity counter', 'Reward counter')$f6$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f7$jsonb_build_array('Earned by', 'Completing lessons', 'Brewing Fuel')$f7$, $r7$jsonb_build_array('How it grows', 'Stays the same', 'Accrues daily while your flame is lit')$r7$)::jsonb where position($f7$jsonb_build_array('Earned by', 'Completing lessons', 'Brewing Fuel')$f7$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f7$jsonb_build_array('Earned by', 'Completing lessons', 'Brewing Fuel')$f7$, $r7$jsonb_build_array('How it grows', 'Stays the same', 'Accrues daily while your flame is lit')$r7$)::jsonb where position($f7$jsonb_build_array('Earned by', 'Completing lessons', 'Brewing Fuel')$f7$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f8$jsonb_build_array('Worth money?', 'No — like XP points', 'Yes — redeemable for USDC')$f8$, $r8$jsonb_build_array('Can you lose it?', 'No — always returned to you', 'Yes — a lapse forfeits it to the community pot')$r8$)::jsonb where position($f8$jsonb_build_array('Worth money?', 'No — like XP points', 'Yes — redeemable for USDC')$f8$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f8$jsonb_build_array('Worth money?', 'No — like XP points', 'Yes — redeemable for USDC')$f8$, $r8$jsonb_build_array('Can you lose it?', 'No — always returned to you', 'Yes — a lapse forfeits it to the community pot')$r8$)::jsonb where position($f8$jsonb_build_array('Worth money?', 'No — like XP points', 'Yes — redeemable for USDC')$f8$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f9$jsonb_build_array('Analogy', 'XP in a game', 'Loyalty points you can cash out')$f9$, $r9$jsonb_build_array('Analogy', 'A security deposit', 'Interest on a savings account')$r9$)::jsonb where position($f9$jsonb_build_array('Analogy', 'XP in a game', 'Loyalty points you can cash out')$f9$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f9$jsonb_build_array('Analogy', 'XP in a game', 'Loyalty points you can cash out')$f9$, $r9$jsonb_build_array('Analogy', 'A security deposit', 'Interest on a savings account')$r9$)::jsonb where position($f9$jsonb_build_array('Analogy', 'XP in a game', 'Loyalty points you can cash out')$f9$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f10$Once you earn Ichor, **nobody can take it away**$f10$, $r10$Once you complete your course, **nobody can block your claim** — your principal and earned yield return to your wallet$r10$)::jsonb where position($f10$Once you earn Ichor, **nobody can take it away**$f10$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f10$Once you earn Ichor, **nobody can take it away**$f10$, $r10$Once you complete your course, **nobody can block your claim** — your principal and earned yield return to your wallet$r10$)::jsonb where position($f10$Once you earn Ichor, **nobody can take it away**$f10$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f11$- **Fuel:** When a user completes a lesson, add Fuel to their counter.$f11$, $r11$- **Yield:** Deposit the locked USDC into Kamino, where it earns real yield while the user learns.$r11$)::jsonb where position($f11$- **Fuel:** When a user completes a lesson, add Fuel to their counter.$f11$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f11$- **Fuel:** When a user completes a lesson, add Fuel to their counter.$f11$, $r11$- **Yield:** Deposit the locked USDC into Kamino, where it earns real yield while the user learns.$r11$)::jsonb where position($f11$- **Fuel:** When a user completes a lesson, add Fuel to their counter.$f11$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f12$- **Brewer:** User can burn Fuel to produce Ichor (both counters in the contract).$f12$, $r12$- **Flame:** When a user completes their daily lesson, keep the flame lit. Yield accrues while the flame is lit.$r12$)::jsonb where position($f12$- **Brewer:** User can burn Fuel to produce Ichor (both counters in the contract).$f12$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f12$- **Brewer:** User can burn Fuel to produce Ichor (both counters in the contract).$f12$, $r12$- **Flame:** When a user completes their daily lesson, keep the flame lit. Yield accrues while the flame is lit.$r12$)::jsonb where position($f12$- **Brewer:** User can burn Fuel to produce Ichor (both counters in the contract).$f12$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f13$- **Streak:** Track daily completion. If streak breaks: drain yield, extend lock.$f13$, $r13$- **Streak:** Track daily completion. If the user lapses after shields are spent: earned yield is forfeited to the community pot — principal is always returned.$r13$)::jsonb where position($f13$- **Streak:** Track daily completion. If streak breaks: drain yield, extend lock.$f13$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f13$- **Streak:** Track daily completion. If streak breaks: drain yield, extend lock.$f13$, $r13$- **Streak:** Track daily completion. If the user lapses after shields are spent: earned yield is forfeited to the community pot — principal is always returned.$r13$)::jsonb where position($f13$- **Streak:** Track daily completion. If streak breaks: drain yield, extend lock.$f13$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f14$Locks USDC, manages Fuel/Ichor, enforces streaks and penalties$f14$, $r14$Locks USDC, deposits it into Kamino for real yield, enforces streaks and lapse penalties$r14$)::jsonb where position($f14$Locks USDC, manages Fuel/Ichor, enforces streaks and penalties$f14$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f14$Locks USDC, manages Fuel/Ichor, enforces streaks and penalties$f14$, $r14$Locks USDC, deposits it into Kamino for real yield, enforces streaks and lapse penalties$r14$)::jsonb where position($f14$Locks USDC, manages Fuel/Ichor, enforces streaks and penalties$f14$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f15$Your Fuel is still recorded.$f15$, $r15$Your yield is still accruing.$r15$)::jsonb where position($f15$Your Fuel is still recorded.$f15$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f15$Your Fuel is still recorded.$f15$, $r15$Your yield is still accruing.$r15$)::jsonb where position($f15$Your Fuel is still recorded.$f15$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f16$'name', 'SOL — Network Fuel', 'desc', 'Solana''s native currency. Pays transaction fees. Price fluctuates like a stock. LockedIn covers your SOL costs.'$f16$, $r16$'name', 'SOL — Pays Network Fees', 'desc', 'Solana''s native currency. Pays transaction fees (gas). Price fluctuates like a stock. LockedIn covers your SOL costs.'$r16$)::jsonb where position($f16$'name', 'SOL — Network Fuel', 'desc', 'Solana''s native currency. Pays transaction fees. Price fluctuates like a stock. LockedIn covers your SOL costs.'$f16$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f16$'name', 'SOL — Network Fuel', 'desc', 'Solana''s native currency. Pays transaction fees. Price fluctuates like a stock. LockedIn covers your SOL costs.'$f16$, $r16$'name', 'SOL — Pays Network Fees', 'desc', 'Solana''s native currency. Pays transaction fees (gas). Price fluctuates like a stock. LockedIn covers your SOL costs.'$r16$)::jsonb where position($f16$'name', 'SOL — Network Fuel', 'desc', 'Solana''s native currency. Pays transaction fees. Price fluctuates like a stock. LockedIn covers your SOL costs.'$f16$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f17$jsonb_build_object('icon', E'\U0001F525', 'name', 'Fuel — Effort Score', 'desc', 'A counter in the smart contract. Earned by completing lessons. Burns into Ichor. **No cash value** — like XP points.'),$f17$, $r17$jsonb_build_object('icon', E'\U0001F525', 'name', 'Flame & Streak — Progress Tracker', 'desc', 'Tracked by the smart contract. Completing a lesson each day keeps your flame lit and your streak alive. **No cash value** — but yield only accrues while it burns.'),$r17$)::jsonb where position($f17$jsonb_build_object('icon', E'\U0001F525', 'name', 'Fuel — Effort Score', 'desc', 'A counter in the smart contract. Earned by completing lessons. Burns into Ichor. **No cash value** — like XP points.'),$f17$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f17$jsonb_build_object('icon', E'\U0001F525', 'name', 'Fuel — Effort Score', 'desc', 'A counter in the smart contract. Earned by completing lessons. Burns into Ichor. **No cash value** — like XP points.'),$f17$, $r17$jsonb_build_object('icon', E'\U0001F525', 'name', 'Flame & Streak — Progress Tracker', 'desc', 'Tracked by the smart contract. Completing a lesson each day keeps your flame lit and your streak alive. **No cash value** — but yield only accrues while it burns.'),$r17$)::jsonb where position($f17$jsonb_build_object('icon', E'\U0001F525', 'name', 'Fuel — Effort Score', 'desc', 'A counter in the smart contract. Earned by completing lessons. Burns into Ichor. **No cash value** — like XP points.'),$f17$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f18$jsonb_build_object('icon', E'⚗', 'name', 'Ichor — Redeemable Reward', 'desc', 'A counter in the smart contract. Brewed from Fuel. **Redeemable for USDC** from the yield pool.')$f18$, $r18$jsonb_build_object('icon', E'\U0001F4C8', 'name', 'Yield — Real Earnings', 'desc', 'Real USDC your locked deposit earns via Kamino while your flame stays lit. **Claimable with your principal** when you finish the course.')$r18$)::jsonb where position($f18$jsonb_build_object('icon', E'⚗', 'name', 'Ichor — Redeemable Reward', 'desc', 'A counter in the smart contract. Brewed from Fuel. **Redeemable for USDC** from the yield pool.')$f18$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f18$jsonb_build_object('icon', E'⚗', 'name', 'Ichor — Redeemable Reward', 'desc', 'A counter in the smart contract. Brewed from Fuel. **Redeemable for USDC** from the yield pool.')$f18$, $r18$jsonb_build_object('icon', E'\U0001F4C8', 'name', 'Yield — Real Earnings', 'desc', 'Real USDC your locked deposit earns via Kamino while your flame stays lit. **Claimable with your principal** when you finish the course.')$r18$)::jsonb where position($f18$jsonb_build_object('icon', E'⚗', 'name', 'Ichor — Redeemable Reward', 'desc', 'A counter in the smart contract. Brewed from Fuel. **Redeemable for USDC** from the yield pool.')$f18$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f19$jsonb_build_array('', 'SOL', 'USDC', 'Fuel', 'Ichor')$f19$, $r19$jsonb_build_array('', 'SOL', 'USDC', 'Streak', 'Yield')$r19$)::jsonb where position($f19$jsonb_build_array('', 'SOL', 'USDC', 'Fuel', 'Ichor')$f19$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f19$jsonb_build_array('', 'SOL', 'USDC', 'Fuel', 'Ichor')$f19$, $r19$jsonb_build_array('', 'SOL', 'USDC', 'Streak', 'Yield')$r19$)::jsonb where position($f19$jsonb_build_array('', 'SOL', 'USDC', 'Fuel', 'Ichor')$f19$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f20$jsonb_build_array('Type', 'SPL Token', 'SPL Token', 'Counter', 'Counter')$f20$, $r20$jsonb_build_array('Type', 'SPL Token', 'SPL Token', 'Counter', 'USDC (accruing)')$r20$)::jsonb where position($f20$jsonb_build_array('Type', 'SPL Token', 'SPL Token', 'Counter', 'Counter')$f20$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f20$jsonb_build_array('Type', 'SPL Token', 'SPL Token', 'Counter', 'Counter')$f20$, $r20$jsonb_build_array('Type', 'SPL Token', 'SPL Token', 'Counter', 'USDC (accruing)')$r20$)::jsonb where position($f20$jsonb_build_array('Type', 'SPL Token', 'SPL Token', 'Counter', 'Counter')$f20$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f21$jsonb_build_array('In your wallet?', 'Yes', 'Yes', 'No — in contract', 'No — in contract')$f21$, $r21$jsonb_build_array('In your wallet?', 'Yes', 'Yes', 'No — in contract', 'No — until you claim')$r21$)::jsonb where position($f21$jsonb_build_array('In your wallet?', 'Yes', 'Yes', 'No — in contract', 'No — in contract')$f21$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f21$jsonb_build_array('In your wallet?', 'Yes', 'Yes', 'No — in contract', 'No — in contract')$f21$, $r21$jsonb_build_array('In your wallet?', 'Yes', 'Yes', 'No — in contract', 'No — until you claim')$r21$)::jsonb where position($f21$jsonb_build_array('In your wallet?', 'Yes', 'Yes', 'No — in contract', 'No — in contract')$f21$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f22$jsonb_build_array('Transferable?', 'Yes', 'Yes', 'No', 'No')$f22$, $r22$jsonb_build_array('Transferable?', 'Yes', 'Yes', 'No', 'Once claimed')$r22$)::jsonb where position($f22$jsonb_build_array('Transferable?', 'Yes', 'Yes', 'No', 'No')$f22$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f22$jsonb_build_array('Transferable?', 'Yes', 'Yes', 'No', 'No')$f22$, $r22$jsonb_build_array('Transferable?', 'Yes', 'Yes', 'No', 'Once claimed')$r22$)::jsonb where position($f22$jsonb_build_array('Transferable?', 'Yes', 'Yes', 'No', 'No')$f22$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f23$'Yes (fluctuates)', 'Yes ($1 always)', 'No', 'Yes (redeemable)'$f23$, $r23$'Yes (fluctuates)', 'Yes ($1 always)', 'No', 'Yes (real USDC)'$r23$)::jsonb where position($f23$'Yes (fluctuates)', 'Yes ($1 always)', 'No', 'Yes (redeemable)'$f23$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f23$'Yes (fluctuates)', 'Yes ($1 always)', 'No', 'Yes (redeemable)'$f23$, $r23$'Yes (fluctuates)', 'Yes ($1 always)', 'No', 'Yes (real USDC)'$r23$)::jsonb where position($f23$'Yes (fluctuates)', 'Yes ($1 always)', 'No', 'Yes (redeemable)'$f23$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f24$Your effort becomes points becomes rewards becomes real money:$f24$, $r24$Your daily effort keeps your flame lit — and your locked USDC earning real money:$r24$)::jsonb where position($f24$Your effort becomes points becomes rewards becomes real money:$f24$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f24$Your effort becomes points becomes rewards becomes real money:$f24$, $r24$Your daily effort keeps your flame lit — and your locked USDC earning real money:$r24$)::jsonb where position($f24$Your effort becomes points becomes rewards becomes real money:$f24$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f25$jsonb_build_object('title', 'Earn Fuel', 'desc', 'Activity counter — tracked in the smart contract', 'icon', E'⚡', 'color', 'amber'),$f25$, $r25$jsonb_build_object('title', 'Keep the flame lit', 'desc', 'Daily streak — tracked in the smart contract', 'icon', E'\U0001F525', 'color', 'amber'),$r25$)::jsonb where position($f25$jsonb_build_object('title', 'Earn Fuel', 'desc', 'Activity counter — tracked in the smart contract', 'icon', E'⚡', 'color', 'amber'),$f25$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f25$jsonb_build_object('title', 'Earn Fuel', 'desc', 'Activity counter — tracked in the smart contract', 'icon', E'⚡', 'color', 'amber'),$f25$, $r25$jsonb_build_object('title', 'Keep the flame lit', 'desc', 'Daily streak — tracked in the smart contract', 'icon', E'\U0001F525', 'color', 'amber'),$r25$)::jsonb where position($f25$jsonb_build_object('title', 'Earn Fuel', 'desc', 'Activity counter — tracked in the smart contract', 'icon', E'⚡', 'color', 'amber'),$f25$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f26$jsonb_build_object('title', 'Brew into Ichor', 'desc', 'The Brewer converts Fuel into redeemable rewards', 'icon', E'⚗', 'color', '#9945FF'),$f26$, $r26$jsonb_build_object('title', 'Yield accrues', 'desc', 'Your locked USDC earns real yield while the flame burns', 'icon', E'\U0001F4C8', 'color', '#9945FF'),$r26$)::jsonb where position($f26$jsonb_build_object('title', 'Brew into Ichor', 'desc', 'The Brewer converts Fuel into redeemable rewards', 'icon', E'⚗', 'color', '#9945FF'),$f26$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f26$jsonb_build_object('title', 'Brew into Ichor', 'desc', 'The Brewer converts Fuel into redeemable rewards', 'icon', E'⚗', 'color', '#9945FF'),$f26$, $r26$jsonb_build_object('title', 'Yield accrues', 'desc', 'Your locked USDC earns real yield while the flame burns', 'icon', E'\U0001F4C8', 'color', '#9945FF'),$r26$)::jsonb where position($f26$jsonb_build_object('title', 'Brew into Ichor', 'desc', 'The Brewer converts Fuel into redeemable rewards', 'icon', E'⚗', 'color', '#9945FF'),$f26$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f27$jsonb_build_object('title', 'Redeem for USDC', 'desc', 'Smart contract burns Ichor and sends USDC to your wallet', 'icon', E'\U0001F4B0', 'color', 'green')$f27$, $r27$jsonb_build_object('title', 'Claim on completion', 'desc', 'Finish the course and the smart contract returns your principal + yield to your wallet', 'icon', E'\U0001F4B0', 'color', 'green')$r27$)::jsonb where position($f27$jsonb_build_object('title', 'Redeem for USDC', 'desc', 'Smart contract burns Ichor and sends USDC to your wallet', 'icon', E'\U0001F4B0', 'color', 'green')$f27$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f27$jsonb_build_object('title', 'Redeem for USDC', 'desc', 'Smart contract burns Ichor and sends USDC to your wallet', 'icon', E'\U0001F4B0', 'color', 'green')$f27$, $r27$jsonb_build_object('title', 'Claim on completion', 'desc', 'Finish the course and the smart contract returns your principal + yield to your wallet', 'icon', E'\U0001F4B0', 'color', 'green')$r27$)::jsonb where position($f27$jsonb_build_object('title', 'Redeem for USDC', 'desc', 'Smart contract burns Ichor and sends USDC to your wallet', 'icon', E'\U0001F4B0', 'color', 'green')$f27$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f28$your USDC is locked, your Fuel is growing, your transactions are on-chain$f28$, $r28$your USDC is locked and earning real yield, your streak is growing, your transactions are on-chain$r28$)::jsonb where position($f28$your USDC is locked, your Fuel is growing, your transactions are on-chain$f28$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f28$your USDC is locked, your Fuel is growing, your transactions are on-chain$f28$, $r28$your USDC is locked and earning real yield, your streak is growing, your transactions are on-chain$r28$)::jsonb where position($f28$your USDC is locked, your Fuel is growing, your transactions are on-chain$f28$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f29$Your USDC is locked. Your Brewer is burning. Your Ichor is flowing.$f29$, $r29$Your USDC is locked. Your flame is lit. Your yield is flowing.$r29$)::jsonb where position($f29$Your USDC is locked. Your Brewer is burning. Your Ichor is flowing.$f29$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f29$Your USDC is locked. Your Brewer is burning. Your Ichor is flowing.$f29$, $r29$Your USDC is locked. Your flame is lit. Your yield is flowing.$r29$)::jsonb where position($f29$Your USDC is locked. Your Brewer is burning. Your Ichor is flowing.$f29$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f30$You've been completing lessons, earning Fuel, maybe brewing some Ichor. But have you wondered — where does the Ichor's value come from?$f30$, $r30$You've been completing lessons, keeping your flame lit, building your streak. But have you wondered — where does the yield you're earning come from?$r30$)::jsonb where position($f30$You've been completing lessons, earning Fuel, maybe brewing some Ichor. But have you wondered — where does the Ichor's value come from?$f30$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f30$You've been completing lessons, earning Fuel, maybe brewing some Ichor. But have you wondered — where does the Ichor's value come from?$f30$, $r30$You've been completing lessons, keeping your flame lit, building your streak. But have you wondered — where does the yield you're earning come from?$r30$)::jsonb where position($f30$You've been completing lessons, earning Fuel, maybe brewing some Ichor. But have you wondered — where does the Ichor's value come from?$f30$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f31$The value behind your Ichor comes from something your locked USDC has been doing this whole time$f31$, $r31$That yield comes from something your locked USDC has been doing this whole time$r31$)::jsonb where position($f31$The value behind your Ichor comes from something your locked USDC has been doing this whole time$f31$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f31$The value behind your Ichor comes from something your locked USDC has been doing this whole time$f31$, $r31$That yield comes from something your locked USDC has been doing this whole time$r31$)::jsonb where position($f31$The value behind your Ichor comes from something your locked USDC has been doing this whole time$f31$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f32$That yield is what funds the Ichor you've been earning.$f32$, $r32$That yield is what you've been earning — and what you'll claim, on top of your principal, when you finish the course.$r32$)::jsonb where position($f32$That yield is what funds the Ichor you've been earning.$f32$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f32$That yield is what funds the Ichor you've been earning.$f32$, $r32$That yield is what you've been earning — and what you'll claim, on top of your principal, when you finish the course.$r32$)::jsonb where position($f32$That yield is what funds the Ichor you've been earning.$f32$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f33$Yield (interest) flows back → Yield funds the Ichor reward pool → You brew Fuel into Ichor, exchangeable for USDC from that pool.$f33$, $r33$Yield (interest) flows back → Yield accrues while your flame stays lit → Finish the course and claim your principal plus the yield it earned.$r33$)::jsonb where position($f33$Yield (interest) flows back → Yield funds the Ichor reward pool → You brew Fuel into Ichor, exchangeable for USDC from that pool.$f33$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f33$Yield (interest) flows back → Yield funds the Ichor reward pool → You brew Fuel into Ichor, exchangeable for USDC from that pool.$f33$, $r33$Yield (interest) flows back → Yield accrues while your flame stays lit → Finish the course and claim your principal plus the yield it earned.$r33$)::jsonb where position($f33$Yield (interest) flows back → Yield funds the Ichor reward pool → You brew Fuel into Ichor, exchangeable for USDC from that pool.$f33$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f34$The Ichor you earn isn't magic. It's backed by real yield$f34$, $r34$The yield you earn isn't magic. It's real yield$r34$)::jsonb where position($f34$The Ichor you earn isn't magic. It's backed by real yield$f34$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f34$The Ichor you earn isn't magic. It's backed by real yield$f34$, $r34$The yield you earn isn't magic. It's real yield$r34$)::jsonb where position($f34$The Ichor you earn isn't magic. It's backed by real yield$f34$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f35$The yield your USDC earns is what backs your Ichor rewards.$f35$, $r35$The yield your USDC earns is yours to claim — keep your flame lit, finish the course, and walk away with your principal plus that yield.$r35$)::jsonb where position($f35$The yield your USDC earns is what backs your Ichor rewards.$f35$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f35$The yield your USDC earns is what backs your Ichor rewards.$f35$, $r35$The yield your USDC earns is yours to claim — keep your flame lit, finish the course, and walk away with your principal plus that yield.$r35$)::jsonb where position($f35$The yield your USDC earns is what backs your Ichor rewards.$f35$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f36$Where does the value behind your Ichor rewards come from?$f36$, $r36$Where does the yield you earn on LockedIn come from?$r36$)::jsonb where position($f36$Where does the value behind your Ichor rewards come from?$f36$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f36$Where does the value behind your Ichor rewards come from?$f36$, $r36$Where does the yield you earn on LockedIn come from?$r36$)::jsonb where position($f36$Where does the value behind your Ichor rewards come from?$f36$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f37$That yield funds the Ichor reward pool → You brew Fuel into Ichor, exchangeable for USDC from that pool.$f37$, $r37$That yield accrues to you while your daily streak keeps your flame lit → Finish the course and claim your principal plus the yield you earned.$r37$)::jsonb where position($f37$That yield funds the Ichor reward pool → You brew Fuel into Ichor, exchangeable for USDC from that pool.$f37$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f37$That yield funds the Ichor reward pool → You brew Fuel into Ichor, exchangeable for USDC from that pool.$f37$, $r37$That yield accrues to you while your daily streak keeps your flame lit → Finish the course and claim your principal plus the yield you earned.$r37$)::jsonb where position($f37$That yield funds the Ichor reward pool → You brew Fuel into Ichor, exchangeable for USDC from that pool.$f37$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f38$That yield funds the Ichor reward pool → You brew Fuel into Ichor.$f38$, $r38$That yield accrues to you while your flame stays lit → Finish the course and claim it along with your principal.$r38$)::jsonb where position($f38$That yield funds the Ichor reward pool → You brew Fuel into Ichor.$f38$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f38$That yield funds the Ichor reward pool → You brew Fuel into Ichor.$f38$, $r38$That yield accrues to you while your flame stays lit → Finish the course and claim it along with your principal.$r38$)::jsonb where position($f38$That yield funds the Ichor reward pool → You brew Fuel into Ichor.$f38$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f39$6, 'callout',
    jsonb_build_object('id','df-2-block-6','type','callout','order',6,'text',$$Quick Recap: DeFi lending = lenders deposit funds into a pool, borrowers pay interest to use them. No bank in the middle — smart contracts manage everything automatically. Borrowers must provide collateral (deposit more than they borrow) so lenders are protected. Your locked USDC is deposited into lending protocols (Kamino/Marginfi) earning yield. That yield is what backs your Ichor rewards — you've been a lender this whole time.$$,'calloutTone','info')$f39$, $r39$6, 'callout',
    jsonb_build_object('id','df-2-block-6','type','callout','order',6,'text',$$Quick Recap: DeFi lending = lenders deposit funds into a pool, borrowers pay interest to use them. No bank in the middle — smart contracts manage everything automatically. Borrowers must provide collateral (deposit more than they borrow) so lenders are protected. Your locked USDC is deposited into lending protocols (Kamino/Marginfi) earning yield. That yield is what you claim, together with your principal, when you finish the course — you've been a lender this whole time.$$,'calloutTone','info')$r39$)::jsonb where position($f39$6, 'callout',
    jsonb_build_object('id','df-2-block-6','type','callout','order',6,'text',$$Quick Recap: DeFi lending = lenders deposit funds into a pool, borrowers pay interest to use them. No bank in the middle — smart contracts manage everything automatically. Borrowers must provide collateral (deposit more than they borrow) so lenders are protected. Your locked USDC is deposited into lending protocols (Kamino/Marginfi) earning yield. That yield is what backs your Ichor rewards — you've been a lender this whole time.$$,'calloutTone','info')$f39$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f39$6, 'callout',
    jsonb_build_object('id','df-2-block-6','type','callout','order',6,'text',$$Quick Recap: DeFi lending = lenders deposit funds into a pool, borrowers pay interest to use them. No bank in the middle — smart contracts manage everything automatically. Borrowers must provide collateral (deposit more than they borrow) so lenders are protected. Your locked USDC is deposited into lending protocols (Kamino/Marginfi) earning yield. That yield is what backs your Ichor rewards — you've been a lender this whole time.$$,'calloutTone','info')$f39$, $r39$6, 'callout',
    jsonb_build_object('id','df-2-block-6','type','callout','order',6,'text',$$Quick Recap: DeFi lending = lenders deposit funds into a pool, borrowers pay interest to use them. No bank in the middle — smart contracts manage everything automatically. Borrowers must provide collateral (deposit more than they borrow) so lenders are protected. Your locked USDC is deposited into lending protocols (Kamino/Marginfi) earning yield. That yield is what you claim, together with your principal, when you finish the course — you've been a lender this whole time.$$,'calloutTone','info')$r39$)::jsonb where position($f39$6, 'callout',
    jsonb_build_object('id','df-2-block-6','type','callout','order',6,'text',$$Quick Recap: DeFi lending = lenders deposit funds into a pool, borrowers pay interest to use them. No bank in the middle — smart contracts manage everything automatically. Borrowers must provide collateral (deposit more than they borrow) so lenders are protected. Your locked USDC is deposited into lending protocols (Kamino/Marginfi) earning yield. That yield is what backs your Ichor rewards — you've been a lender this whole time.$$,'calloutTone','info')$f39$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f40$      jsonb_build_object('id','df-2-block-6','type','callout','order',6,'text',$$Quick Recap: DeFi lending = lenders deposit funds into a pool, borrowers pay interest to use them. No bank in the middle — smart contracts manage everything automatically. Borrowers must provide collateral (deposit more than they borrow) so lenders are protected. Your locked USDC is deposited into lending protocols (Kamino/Marginfi) earning yield. That yield is what backs your Ichor rewards — you've been a lender this whole time.$$,'calloutTone','info')$f40$, $r40$      jsonb_build_object('id','df-2-block-6','type','callout','order',6,'text',$$Quick Recap: DeFi lending = lenders deposit funds into a pool, borrowers pay interest to use them. No bank in the middle — smart contracts manage everything automatically. Borrowers must provide collateral (deposit more than they borrow) so lenders are protected. Your locked USDC is deposited into lending protocols (Kamino/Marginfi) earning yield. That yield is what you claim, together with your principal, when you finish the course — you've been a lender this whole time.$$,'calloutTone','info')$r40$)::jsonb where position($f40$      jsonb_build_object('id','df-2-block-6','type','callout','order',6,'text',$$Quick Recap: DeFi lending = lenders deposit funds into a pool, borrowers pay interest to use them. No bank in the middle — smart contracts manage everything automatically. Borrowers must provide collateral (deposit more than they borrow) so lenders are protected. Your locked USDC is deposited into lending protocols (Kamino/Marginfi) earning yield. That yield is what backs your Ichor rewards — you've been a lender this whole time.$$,'calloutTone','info')$f40$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f40$      jsonb_build_object('id','df-2-block-6','type','callout','order',6,'text',$$Quick Recap: DeFi lending = lenders deposit funds into a pool, borrowers pay interest to use them. No bank in the middle — smart contracts manage everything automatically. Borrowers must provide collateral (deposit more than they borrow) so lenders are protected. Your locked USDC is deposited into lending protocols (Kamino/Marginfi) earning yield. That yield is what backs your Ichor rewards — you've been a lender this whole time.$$,'calloutTone','info')$f40$, $r40$      jsonb_build_object('id','df-2-block-6','type','callout','order',6,'text',$$Quick Recap: DeFi lending = lenders deposit funds into a pool, borrowers pay interest to use them. No bank in the middle — smart contracts manage everything automatically. Borrowers must provide collateral (deposit more than they borrow) so lenders are protected. Your locked USDC is deposited into lending protocols (Kamino/Marginfi) earning yield. That yield is what you claim, together with your principal, when you finish the course — you've been a lender this whole time.$$,'calloutTone','info')$r40$)::jsonb where position($f40$      jsonb_build_object('id','df-2-block-6','type','callout','order',6,'text',$$Quick Recap: DeFi lending = lenders deposit funds into a pool, borrowers pay interest to use them. No bank in the middle — smart contracts manage everything automatically. Borrowers must provide collateral (deposit more than they borrow) so lenders are protected. Your locked USDC is deposited into lending protocols (Kamino/Marginfi) earning yield. That yield is what backs your Ichor rewards — you've been a lender this whole time.$$,'calloutTone','info')$f40$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f41$Yield flows into the Ichor reward pool → LockedIn takes a 10-20% fee from yield (LockedIn's revenue) → Remaining yield is available to users via Ichor → Users who stay consistent brew Fuel into Ichor and exchange for USDC. Users who slack have yield redistributed (penalties).$f41$, $r41$Yield accrues to your lock while your daily flame stays lit → LockedIn takes a 10-20% fee from yield (LockedIn's revenue) → Remaining yield is yours to claim, along with your principal, when you finish the course. Users who lapse (miss days after their shields are spent) forfeit their yield to the community pot — principal is always returned.$r41$)::jsonb where position($f41$Yield flows into the Ichor reward pool → LockedIn takes a 10-20% fee from yield (LockedIn's revenue) → Remaining yield is available to users via Ichor → Users who stay consistent brew Fuel into Ichor and exchange for USDC. Users who slack have yield redistributed (penalties).$f41$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f41$Yield flows into the Ichor reward pool → LockedIn takes a 10-20% fee from yield (LockedIn's revenue) → Remaining yield is available to users via Ichor → Users who stay consistent brew Fuel into Ichor and exchange for USDC. Users who slack have yield redistributed (penalties).$f41$, $r41$Yield accrues to your lock while your daily flame stays lit → LockedIn takes a 10-20% fee from yield (LockedIn's revenue) → Remaining yield is yours to claim, along with your principal, when you finish the course. Users who lapse (miss days after their shields are spent) forfeit their yield to the community pot — principal is always returned.$r41$)::jsonb where position($f41$Yield flows into the Ichor reward pool → LockedIn takes a 10-20% fee from yield (LockedIn's revenue) → Remaining yield is available to users via Ichor → Users who stay consistent brew Fuel into Ichor and exchange for USDC. Users who slack have yield redistributed (penalties).$f41$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f42$Rates fluctuate based on supply and demand. LockedIn takes 10-20% of yield as revenue. The rest funds your Ichor rewards.$f42$, $r42$Rates fluctuate based on supply and demand. LockedIn takes 10-20% of yield as revenue. The rest is yield you claim, along with your principal, when you finish the course.$r42$)::jsonb where position($f42$Rates fluctuate based on supply and demand. LockedIn takes 10-20% of yield as revenue. The rest funds your Ichor rewards.$f42$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f42$Rates fluctuate based on supply and demand. LockedIn takes 10-20% of yield as revenue. The rest funds your Ichor rewards.$f42$, $r42$Rates fluctuate based on supply and demand. LockedIn takes 10-20% of yield as revenue. The rest is yield you claim, along with your principal, when you finish the course.$r42$)::jsonb where position($f42$Rates fluctuate based on supply and demand. LockedIn takes 10-20% of yield as revenue. The rest funds your Ichor rewards.$f42$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f43$3-8% APY → Ichor reward pool → LockedIn takes 10-20% fee → Rest available to users via Ichor.$f43$, $r43$3-8% APY → yield accrues while your flame stays lit → LockedIn takes 10-20% fee → Rest is claimable with your principal when you finish the course.$r43$)::jsonb where position($f43$3-8% APY → Ichor reward pool → LockedIn takes 10-20% fee → Rest available to users via Ichor.$f43$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f43$3-8% APY → Ichor reward pool → LockedIn takes 10-20% fee → Rest available to users via Ichor.$f43$, $r43$3-8% APY → yield accrues while your flame stays lit → LockedIn takes 10-20% fee → Rest is claimable with your principal when you finish the course.$r43$)::jsonb where position($f43$3-8% APY → Ichor reward pool → LockedIn takes 10-20% fee → Rest available to users via Ichor.$f43$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f44$APY = compound interest rate. LockedIn takes 10-20% of yield as revenue. The rest funds your Ichor rewards.$f44$, $r44$APY = compound interest rate. LockedIn takes 10-20% of yield as revenue. The rest is yield you claim, along with your principal, when you finish the course.$r44$)::jsonb where position($f44$APY = compound interest rate. LockedIn takes 10-20% of yield as revenue. The rest funds your Ichor rewards.$f44$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f44$APY = compound interest rate. LockedIn takes 10-20% of yield as revenue. The rest funds your Ichor rewards.$f44$, $r44$APY = compound interest rate. LockedIn takes 10-20% of yield as revenue. The rest is yield you claim, along with your principal, when you finish the course.$r44$)::jsonb where position($f44$APY = compound interest rate. LockedIn takes 10-20% of yield as revenue. The rest funds your Ichor rewards.$f44$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f45$- When Ichor is exchanged for USDC from the yield pool$f45$, $r45$- When earned yield needs to be converted to USDC for your claim$r45$)::jsonb where position($f45$- When Ichor is exchanged for USDC from the yield pool$f45$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f45$- When Ichor is exchanged for USDC from the yield pool$f45$, $r45$- When earned yield needs to be converted to USDC for your claim$r45$)::jsonb where position($f45$- When Ichor is exchanged for USDC from the yield pool$f45$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f46$          LockedIn fee    Ichor Reward Pool
          (10-20%)             │
                          Your Ichor
                               │
                       Jupiter (swap layer)
                               │
                          USDC payout$$)
  ),$f46$, $r46$        Finish course       Lapse (shields spent)
              │                      │
      Claim principal        Yield forfeited to
      + earned yield          community pot
       (USDC payout)        (principal returned)$$)
  ),$r46$)::jsonb where position($f46$          LockedIn fee    Ichor Reward Pool
          (10-20%)             │
                          Your Ichor
                               │
                       Jupiter (swap layer)
                               │
                          USDC payout$$)
  ),$f46$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f46$          LockedIn fee    Ichor Reward Pool
          (10-20%)             │
                          Your Ichor
                               │
                       Jupiter (swap layer)
                               │
                          USDC payout$$)
  ),$f46$, $r46$        Finish course       Lapse (shields spent)
              │                      │
      Claim principal        Yield forfeited to
      + earned yield          community pot
       (USDC payout)        (principal returned)$$)
  ),$r46$)::jsonb where position($f46$          LockedIn fee    Ichor Reward Pool
          (10-20%)             │
                          Your Ichor
                               │
                       Jupiter (swap layer)
                               │
                          USDC payout$$)
  ),$f46$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f47$          LockedIn fee    Ichor Reward Pool
          (10-20%)             │
                          Your Ichor
                               │
                       Jupiter (swap layer)
                               │
                          USDC payout$$),$f47$, $r47$        Finish course       Lapse (shields spent)
              │                      │
      Claim principal        Yield forfeited to
      + earned yield          community pot
       (USDC payout)        (principal returned)$$),$r47$)::jsonb where position($f47$          LockedIn fee    Ichor Reward Pool
          (10-20%)             │
                          Your Ichor
                               │
                       Jupiter (swap layer)
                               │
                          USDC payout$$),$f47$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f47$          LockedIn fee    Ichor Reward Pool
          (10-20%)             │
                          Your Ichor
                               │
                       Jupiter (swap layer)
                               │
                          USDC payout$$),$f47$, $r47$        Finish course       Lapse (shields spent)
              │                      │
      Claim principal        Yield forfeited to
      + earned yield          community pot
       (USDC payout)        (principal returned)$$),$r47$)::jsonb where position($f47$          LockedIn fee    Ichor Reward Pool
          (10-20%)             │
                          Your Ichor
                               │
                       Jupiter (swap layer)
                               │
                          USDC payout$$),$f47$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f48$Just means variable Ichor rewards.$f48$, $r48$Just means the yield accruing on your locked USDC varies.$r48$)::jsonb where position($f48$Just means variable Ichor rewards.$f48$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f48$Just means variable Ichor rewards.$f48$, $r48$Just means the yield accruing on your locked USDC varies.$r48$)::jsonb where position($f48$Just means variable Ichor rewards.$f48$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f49$Tokens (SOL, USDC) and counters (Fuel, Ichor).$f49$, $r49$Tokens (SOL, USDC) and how SOL pays network transaction fees.$r49$)::jsonb where position($f49$Tokens (SOL, USDC) and counters (Fuel, Ichor).$f49$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f49$Tokens (SOL, USDC) and counters (Fuel, Ichor).$f49$, $r49$Tokens (SOL, USDC) and how SOL pays network transaction fees.$r49$)::jsonb where position($f49$Tokens (SOL, USDC) and counters (Fuel, Ichor).$f49$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f50$Earn Fuel. Brew Ichor.$f50$, $r50$Keep your flame lit. Build your streak.$r50$)::jsonb where position($f50$Earn Fuel. Brew Ichor.$f50$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f50$Earn Fuel. Brew Ichor.$f50$, $r50$Keep your flame lit. Build your streak.$r50$)::jsonb where position($f50$Earn Fuel. Brew Ichor.$f50$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f51$Earning Ichor and exchanging it for USDC may create a tax event.$f51$, $r51$Claiming your earned yield when you finish a course may create a tax event.$r51$)::jsonb where position($f51$Earning Ichor and exchanging it for USDC may create a tax event.$f51$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f51$Earning Ichor and exchanging it for USDC may create a tax event.$f51$, $r51$Claiming your earned yield when you finish a course may create a tax event.$r51$)::jsonb where position($f51$Earning Ichor and exchanging it for USDC may create a tax event.$f51$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f52$for the next era.

Your USDC is locked. Your yield is flowing. Your Ichor is brewing.$f52$, $r52$for the next era.

Your USDC is locked. Your yield is flowing. Your flame is lit.$r52$)::jsonb where position($f52$for the next era.

Your USDC is locked. Your yield is flowing. Your Ichor is brewing.$f52$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f52$for the next era.

Your USDC is locked. Your yield is flowing. Your Ichor is brewing.$f52$, $r52$for the next era.

Your USDC is locked. Your yield is flowing. Your flame is lit.$r52$)::jsonb where position($f52$for the next era.

Your USDC is locked. Your yield is flowing. Your Ichor is brewing.$f52$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f53$'order',4,'text',$$Your USDC is locked. Your yield is flowing. Your Ichor is brewing.$f53$, $r53$'order',4,'text',$$Your USDC is locked. Your yield is flowing. Your flame is lit.$r53$)::jsonb where position($f53$'order',4,'text',$$Your USDC is locked. Your yield is flowing. Your Ichor is brewing.$f53$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f53$'order',4,'text',$$Your USDC is locked. Your yield is flowing. Your Ichor is brewing.$f53$, $r53$'order',4,'text',$$Your USDC is locked. Your yield is flowing. Your flame is lit.$r53$)::jsonb where position($f53$'order',4,'text',$$Your USDC is locked. Your yield is flowing. Your Ichor is brewing.$f53$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f54$Ichor — Redeemable Reward$f54$, $r54$Yield — Your Reward$r54$)::jsonb where position($f54$Ichor — Redeemable Reward$f54$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f54$Ichor — Redeemable Reward$f54$, $r54$Yield — Your Reward$r54$)::jsonb where position($f54$Ichor — Redeemable Reward$f54$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f55$A counter in the smart contract. Brewed from Fuel. **Redeemable for USDC** from the yield pool.$f55$, $r55$Real interest your locked USDC earns in Kamino while your flame stays lit. **Paid in USDC** when you claim on course completion.$r55$)::jsonb where position($f55$A counter in the smart contract. Brewed from Fuel. **Redeemable for USDC** from the yield pool.$f55$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f55$A counter in the smart contract. Brewed from Fuel. **Redeemable for USDC** from the yield pool.$f55$, $r55$Real interest your locked USDC earns in Kamino while your flame stays lit. **Paid in USDC** when you claim on course completion.$r55$)::jsonb where position($f55$A counter in the smart contract. Brewed from Fuel. **Redeemable for USDC** from the yield pool.$f55$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f56$'Earn Fuel', 'desc', 'Activity counter — tracked in the smart contract'$f56$, $r56$'Keep the flame lit', 'desc', 'Daily completion keeps your yield accruing'$r56$)::jsonb where position($f56$'Earn Fuel', 'desc', 'Activity counter — tracked in the smart contract'$f56$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f56$'Earn Fuel', 'desc', 'Activity counter — tracked in the smart contract'$f56$, $r56$'Keep the flame lit', 'desc', 'Daily completion keeps your yield accruing'$r56$)::jsonb where position($f56$'Earn Fuel', 'desc', 'Activity counter — tracked in the smart contract'$f56$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f57$'Brew into Ichor', 'desc', 'The Brewer converts Fuel into redeemable rewards'$f57$, $r57$'Earn yield', 'desc', 'Your locked USDC earns real interest via Kamino'$r57$)::jsonb where position($f57$'Brew into Ichor', 'desc', 'The Brewer converts Fuel into redeemable rewards'$f57$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f57$'Brew into Ichor', 'desc', 'The Brewer converts Fuel into redeemable rewards'$f57$, $r57$'Earn yield', 'desc', 'Your locked USDC earns real interest via Kamino'$r57$)::jsonb where position($f57$'Brew into Ichor', 'desc', 'The Brewer converts Fuel into redeemable rewards'$f57$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f58$["", "SOL", "USDC", "Fuel", "Ichor"]$f58$, $r58$["", "SOL", "USDC", "Streak", "Yield"]$r58$)::jsonb where position($f58$["", "SOL", "USDC", "Fuel", "Ichor"]$f58$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f58$["", "SOL", "USDC", "Fuel", "Ichor"]$f58$, $r58$["", "SOL", "USDC", "Streak", "Yield"]$r58$)::jsonb where position($f58$["", "SOL", "USDC", "Fuel", "Ichor"]$f58$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f59$["", "Fuel", "Ichor"]$f59$, $r59$["", "Principal", "Yield"]$r59$)::jsonb where position($f59$["", "Fuel", "Ichor"]$f59$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f59$["", "Fuel", "Ichor"]$f59$, $r59$["", "Principal", "Yield"]$r59$)::jsonb where position($f59$["", "Fuel", "Ichor"]$f59$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f60$"Brewing Fuel"$f60$, $r60$"Earning yield"$r60$)::jsonb where position($f60$"Brewing Fuel"$f60$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f60$"Brewing Fuel"$f60$, $r60$"Earning yield"$r60$)::jsonb where position($f60$"Brewing Fuel"$f60$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f61$SOL — Network Fuel$f61$, $r61$SOL — Pays Network Fees$r61$)::jsonb where position($f61$SOL — Network Fuel$f61$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f61$SOL — Network Fuel$f61$, $r61$SOL — Pays Network Fees$r61$)::jsonb where position($f61$SOL — Network Fuel$f61$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f62$Fuel — Effort Score$f62$, $r62$Flame — Progress Tracker$r62$)::jsonb where position($f62$Fuel — Effort Score$f62$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f62$Fuel — Effort Score$f62$, $r62$Flame — Progress Tracker$r62$)::jsonb where position($f62$Fuel — Effort Score$f62$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f63$The Brewer converts Fuel into redeemable rewards$f63$, $r63$Your locked USDC earns real yield via Kamino$r63$)::jsonb where position($f63$The Brewer converts Fuel into redeemable rewards$f63$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f63$The Brewer converts Fuel into redeemable rewards$f63$, $r63$Your locked USDC earns real yield via Kamino$r63$)::jsonb where position($f63$The Brewer converts Fuel into redeemable rewards$f63$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f64$Earned by completing lessons. Burns into Ichor. **No cash value** — like XP points.$f64$, $r64$Kept lit by completing a lesson each day. **No cash value** — but yield only accrues while it burns.$r64$)::jsonb where position($f64$Earned by completing lessons. Burns into Ichor. **No cash value** — like XP points.$f64$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f64$Earned by completing lessons. Burns into Ichor. **No cash value** — like XP points.$f64$, $r64$Kept lit by completing a lesson each day. **No cash value** — but yield only accrues while it burns.$r64$)::jsonb where position($f64$Earned by completing lessons. Burns into Ichor. **No cash value** — like XP points.$f64$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f65$Your USDC is locked. Your yield is flowing. Your Ichor is brewing.$f65$, $r65$Your USDC is locked. Your yield is flowing and accruing.$r65$)::jsonb where position($f65$Your USDC is locked. Your yield is flowing. Your Ichor is brewing.$f65$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f65$Your USDC is locked. Your yield is flowing. Your Ichor is brewing.$f65$, $r65$Your USDC is locked. Your yield is flowing and accruing.$r65$)::jsonb where position($f65$Your USDC is locked. Your yield is flowing. Your Ichor is brewing.$f65$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f66$backs your Ichor rewards$f66$, $r66$backs your yield$r66$)::jsonb where position($f66$backs your Ichor rewards$f66$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f66$backs your Ichor rewards$f66$, $r66$backs your yield$r66$)::jsonb where position($f66$backs your Ichor rewards$f66$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f67$Smart contract burns Ichor and sends USDC to your wallet$f67$, $r67$Smart contract returns your principal and yield to your wallet$r67$)::jsonb where position($f67$Smart contract burns Ichor and sends USDC to your wallet$f67$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f67$Smart contract burns Ichor and sends USDC to your wallet$f67$, $r67$Smart contract returns your principal and yield to your wallet$r67$)::jsonb where position($f67$Smart contract burns Ichor and sends USDC to your wallet$f67$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f68$test locking, streaks, fuel, and withdrawal$f68$, $r68$test locking, streaks, and withdrawal$r68$)::jsonb where position($f68$test locking, streaks, fuel, and withdrawal$f68$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f68$test locking, streaks, fuel, and withdrawal$f68$, $r68$test locking, streaks, and withdrawal$r68$)::jsonb where position($f68$test locking, streaks, fuel, and withdrawal$f68$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f69$Ichor Reward Pool$f69$, $r69$the Community Pot$r69$)::jsonb where position($f69$Ichor Reward Pool$f69$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f69$Ichor Reward Pool$f69$, $r69$the Community Pot$r69$)::jsonb where position($f69$Ichor Reward Pool$f69$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f70$Earn Fuel$f70$, $r70$Keep flame lit$r70$)::jsonb where position($f70$Earn Fuel$f70$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f70$Earn Fuel$f70$, $r70$Keep flame lit$r70$)::jsonb where position($f70$Earn Fuel$f70$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f71$Brew into Ichor$f71$, $r71$Earn yield$r71$)::jsonb where position($f71$Brew into Ichor$f71$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f71$Brew into Ichor$f71$, $r71$Earn yield$r71$)::jsonb where position($f71$Brew into Ichor$f71$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f72$Your Ichor$f72$, $r72$Your Yield$r72$)::jsonb where position($f72$Your Ichor$f72$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f72$Your Ichor$f72$, $r72$Your Yield$r72$)::jsonb where position($f72$Your Ichor$f72$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f73$Network Fuel$f73$, $r73$Gas token$r73$)::jsonb where position($f73$Network Fuel$f73$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f73$Network Fuel$f73$, $r73$Gas token$r73$)::jsonb where position($f73$Network Fuel$f73$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f74$SOL fuel gas transaction fees fluctuates USDC stable dollar always one$f74$, $r74$SOL gas transaction fees fluctuates USDC stable dollar always one$r74$)::jsonb where position($f74$SOL fuel gas transaction fees fluctuates USDC stable dollar always one$f74$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f74$SOL fuel gas transaction fees fluctuates USDC stable dollar always one$f74$, $r74$SOL gas transaction fees fluctuates USDC stable dollar always one$r74$)::jsonb where position($f74$SOL fuel gas transaction fees fluctuates USDC stable dollar always one$f74$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f75$What's the difference between Fuel and Ichor?$f75$, $r75$In your lock, what is the difference between your principal and your yield?$r75$)::jsonb where position($f75$What's the difference between Fuel and Ichor?$f75$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f75$What's the difference between Fuel and Ichor?$f75$, $r75$In your lock, what is the difference between your principal and your yield?$r75$)::jsonb where position($f75$What's the difference between Fuel and Ichor?$f75$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f76$Both are counters, but Ichor can be redeemed for USDC while Fuel cannot$f76$, $r76$Principal is your locked USDC, always returned; yield is the interest it earns, forfeited only if you lapse$r76$)::jsonb where position($f76$Both are counters, but Ichor can be redeemed for USDC while Fuel cannot$f76$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f76$Both are counters, but Ichor can be redeemed for USDC while Fuel cannot$f76$, $r76$Principal is your locked USDC, always returned; yield is the interest it earns, forfeited only if you lapse$r76$)::jsonb where position($f76$Both are counters, but Ichor can be redeemed for USDC while Fuel cannot$f76$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f77$Both are counters, but Ichor can be redeemed for USDC while Fuel cannot$f77$, $r77$Principal is your locked USDC, always returned; yield is the interest it earns, forfeited only if you lapse$r77$)::jsonb where position($f77$Both are counters, but Ichor can be redeemed for USDC while Fuel cannot$f77$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f77$Both are counters, but Ichor can be redeemed for USDC while Fuel cannot$f77$, $r77$Principal is your locked USDC, always returned; yield is the interest it earns, forfeited only if you lapse$r77$)::jsonb where position($f77$Both are counters, but Ichor can be redeemed for USDC while Fuel cannot$f77$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f78$Fuel is worth more money than Ichor$f78$, $r78$Yield is worth more money than your principal$r78$)::jsonb where position($f78$Fuel is worth more money than Ichor$f78$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f78$Fuel is worth more money than Ichor$f78$, $r78$Yield is worth more money than your principal$r78$)::jsonb where position($f78$Fuel is worth more money than Ichor$f78$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f79$What happens when you redeem Ichor?$f79$, $r79$What happens when you claim after finishing a course?$r79$)::jsonb where position($f79$What happens when you redeem Ichor?$f79$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f79$What happens when you redeem Ichor?$f79$, $r79$What happens when you claim after finishing a course?$r79$)::jsonb where position($f79$What happens when you redeem Ichor?$f79$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f80$The smart contract burns your Ichor counter and sends USDC to your wallet$f80$, $r80$The smart contract returns your principal plus the yield it earned to your wallet$r80$)::jsonb where position($f80$The smart contract burns your Ichor counter and sends USDC to your wallet$f80$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f80$The smart contract burns your Ichor counter and sends USDC to your wallet$f80$, $r80$The smart contract returns your principal plus the yield it earned to your wallet$r80$)::jsonb where position($f80$The smart contract burns your Ichor counter and sends USDC to your wallet$f80$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f81$The smart contract burns your Ichor counter and sends USDC to your wallet$f81$, $r81$The smart contract returns your principal plus the yield it earned to your wallet$r81$)::jsonb where position($f81$The smart contract burns your Ichor counter and sends USDC to your wallet$f81$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f81$The smart contract burns your Ichor counter and sends USDC to your wallet$f81$, $r81$The smart contract returns your principal plus the yield it earned to your wallet$r81$)::jsonb where position($f81$The smart contract burns your Ichor counter and sends USDC to your wallet$f81$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f82$Ichor is converted to SOL and then to USDC$f82$, $r82$Your yield is converted to SOL and then to USDC$r82$)::jsonb where position($f82$Ichor is converted to SOL and then to USDC$f82$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f82$Ichor is converted to SOL and then to USDC$f82$, $r82$Your yield is converted to SOL and then to USDC$r82$)::jsonb where position($f82$Ichor is converted to SOL and then to USDC$f82$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f83$Ichor tokens are sent directly to your wallet$f83$, $r83$Tokens are sent to you from LockedIn's own funds$r83$)::jsonb where position($f83$Ichor tokens are sent directly to your wallet$f83$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f83$Ichor tokens are sent directly to your wallet$f83$, $r83$Tokens are sent to you from LockedIn's own funds$r83$)::jsonb where position($f83$Ichor tokens are sent directly to your wallet$f83$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f84$Explain the difference between a token (like USDC) and a counter (like Fuel).$f84$, $r84$Explain the difference between a token (like USDC) and a counter (like your streak).$r84$)::jsonb where position($f84$Explain the difference between a token (like USDC) and a counter (like Fuel).$f84$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f84$Explain the difference between a token (like USDC) and a counter (like Fuel).$f84$, $r84$Explain the difference between a token (like USDC) and a counter (like your streak).$r84$)::jsonb where position($f84$Explain the difference between a token (like USDC) and a counter (like Fuel).$f84$ in payload::text) > 0;
  update lesson.lesson_blocks set payload = replace(payload::text, $f85$Where does the value behind your Ichor rewards come from?$f85$, $r85$Where does the yield on your locked USDC come from?$r85$)::jsonb where position($f85$Where does the value behind your Ichor rewards come from?$f85$ in payload::text) > 0;
  update lesson.published_lesson_payloads set payload = replace(payload::text, $f85$Where does the value behind your Ichor rewards come from?$f85$, $r85$Where does the yield on your locked USDC come from?$r85$)::jsonb where position($f85$Where does the value behind your Ichor rewards come from?$f85$ in payload::text) > 0;
  update lesson.questions set correct_answer = $qc0$SOL gas transaction fees fluctuates USDC stable dollar always one$qc0$ where id = $qi0$bw-2-q4$qi0$;
  update lesson.questions set prompt = $qp1$In your lock, what is the difference between your principal and your yield?$qp1$, correct_answer = $qc1$Principal is your locked USDC, always returned; yield is the interest it earns, forfeited only if you lapse$qc1$ where id = $qi1$bw-4-q1$qi1$;
  update lesson.question_options set option_text = $ot2$Principal is your locked USDC, always returned; yield is the interest it earns, forfeited only if you lapse$ot2$ where id = $oi2$0ab30af1-bee7-4918-ae4b-a27828d63893$oi2$;
  update lesson.question_options set option_text = $ot3$Yield is worth more money than your principal$ot3$ where id = $oi3$7c5c4490-2626-438e-9ac2-6054823ae79b$oi3$;
  update lesson.questions set prompt = $qp4$What happens when you claim after finishing a course?$qp4$, correct_answer = $qc4$The smart contract returns your principal plus the yield it earned to your wallet$qc4$ where id = $qi4$bw-6-q1$qi4$;
  update lesson.question_options set option_text = $ot5$The smart contract returns your principal plus the yield it earned to your wallet$ot5$ where id = $oi5$d7c9414c-19a2-487e-be85-5c9ab239c65c$oi5$;
  update lesson.question_options set option_text = $ot6$Your yield is converted to SOL and then to USDC$ot6$ where id = $oi6$5953350b-c3cb-4d55-8a0f-f690c946deb5$oi6$;
  update lesson.question_options set option_text = $ot7$Tokens are sent to you from LockedIn's own funds$ot7$ where id = $oi7$0f898b9a-9f96-4f87-84a0-23d1f06b2582$oi7$;
  update lesson.questions set prompt = $qp8$Explain the difference between a token (like USDC) and a counter (like your streak).$qp8$ where id = $qi8$bw-6-q4$qi8$;
  update lesson.questions set prompt = $qp9$Where does the yield on your locked USDC come from?$qp9$ where id = $qi9$df-1-q1$qi9$;
end
$mig$;
